/*
 * generated by Xtext 2.21.0
 */
package org.example.ehealthmanagement.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EHealthManagementUiModule extends AbstractEHealthManagementUiModule {

	public EHealthManagementUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
