/*
 * generated by Xtext 2.21.0
 */
package org.example.ehealthmanagement.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EHealthManagementStandaloneSetup extends EHealthManagementStandaloneSetupGenerated {

	public static void doSetup() {
		new EHealthManagementStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
