/*
 * generated by Xtext 2.21.0
 */
package org.example.ehealthmanagement.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEHealthManagementScopeProvider extends DelegatingScopeProvider {
}
