/*
 * generated by Xtext 2.21.0
 */
package org.example.ehealthmanagement.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.example.ehealthmanagement.xtext.ui.internal.XtextActivator;

public class EHealthManagementUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("org.example.ehealthmanagement.xtext.EHealthManagement");
	}

}
