/*
 * generated by Xtext 2.21.0
 */
package org.example.ehealthmanagement.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EHealthManagementAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/example/ehealthmanagement/xtext/parser/antlr/internal/InternalEHealthManagement.tokens");
	}
}
