package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_AllowedUsertypes extends EnumerationDescriptorBase {

  public EnumerationDescriptor_AllowedUsertypes() {
    super(0x59f9da20e62a4a82L, 0x8c2d8a77f06056f1L, 0x68bcf0507dc9f3eaL, "AllowedUsertypes", "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304064545770");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Doctor_0 = new EnumerationDescriptor.MemberDescriptor("Doctor", "Doctor", 0x68bcf0507dc9f3ebL, "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304064545771");
  private final EnumerationDescriptor.MemberDescriptor myMember_Patient_0 = new EnumerationDescriptor.MemberDescriptor("Patient", "Patient", 0x68bcf0507dc9f5baL, "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304064546234");
  private final EnumerationDescriptor.MemberDescriptor myMember_SystemAdmin_0 = new EnumerationDescriptor.MemberDescriptor("SystemAdmin", "SystemAdmin", 0x68bcf0507dc9f5bdL, "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304064546237");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x59f9da20e62a4a82L, 0x8c2d8a77f06056f1L, 0x68bcf0507dc9f3eaL, 0x68bcf0507dc9f3ebL, 0x68bcf0507dc9f5baL, 0x68bcf0507dc9f5bdL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Doctor_0, myMember_Patient_0, myMember_SystemAdmin_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Doctor":
        return myMember_Doctor_0;
      case "Patient":
        return myMember_Patient_0;
      case "SystemAdmin":
        return myMember_SystemAdmin_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
