package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_AllowedRepresentationTypes extends EnumerationDescriptorBase {

  public EnumerationDescriptor_AllowedRepresentationTypes() {
    super(0x59f9da20e62a4a82L, 0x8c2d8a77f06056f1L, 0x68bcf0507dd993ccL, "AllowedRepresentationTypes", "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304065569740");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_PatientList_0 = new EnumerationDescriptor.MemberDescriptor("PatientList", "PatientList", 0x68bcf0507ddf96e8L, "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304065963752");
  private final EnumerationDescriptor.MemberDescriptor myMember_PatientDetails_0 = new EnumerationDescriptor.MemberDescriptor("PatientDetails", "PatientDetails", 0x68bcf0507ddf9706L, "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304065963782");
  private final EnumerationDescriptor.MemberDescriptor myMember_ProfilePage_0 = new EnumerationDescriptor.MemberDescriptor("ProfilePage", "ProfilePage", 0x68bcf0507ddf970fL, "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304065963791");
  private final EnumerationDescriptor.MemberDescriptor myMember_PatientInteraction_0 = new EnumerationDescriptor.MemberDescriptor("PatientInteraction", "PatientInteraction", 0x68bcf0507ddf971aL, "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304065963802");
  private final EnumerationDescriptor.MemberDescriptor myMember_Notification_0 = new EnumerationDescriptor.MemberDescriptor("Notification", "Notification", 0x68bcf0507dd99bd8L, "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304065571800");
  private final EnumerationDescriptor.MemberDescriptor myMember_MedicineList_0 = new EnumerationDescriptor.MemberDescriptor("MedicineList", "MedicineList", 0x68bcf0507ddf9727L, "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304065963815");
  private final EnumerationDescriptor.MemberDescriptor myMember_PatientDocuments_0 = new EnumerationDescriptor.MemberDescriptor("PatientDocuments", "PatientDocuments", 0x68bcf0507ddf9736L, "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304065963830");
  private final EnumerationDescriptor.MemberDescriptor myMember_PatientReports_0 = new EnumerationDescriptor.MemberDescriptor("PatientReports", "PatientReports", 0x68bcf0507ddf976aL, "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304065963882");
  private final EnumerationDescriptor.MemberDescriptor myMember_PopUpPage_0 = new EnumerationDescriptor.MemberDescriptor("PopUpPage", "PopUpPage", 0x68bcf0507dd99bddL, "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304065571805");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x59f9da20e62a4a82L, 0x8c2d8a77f06056f1L, 0x68bcf0507dd993ccL, 0x68bcf0507ddf96e8L, 0x68bcf0507ddf9706L, 0x68bcf0507ddf970fL, 0x68bcf0507ddf971aL, 0x68bcf0507dd99bd8L, 0x68bcf0507ddf9727L, 0x68bcf0507ddf9736L, 0x68bcf0507ddf976aL, 0x68bcf0507dd99bddL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_PatientList_0, myMember_PatientDetails_0, myMember_ProfilePage_0, myMember_PatientInteraction_0, myMember_Notification_0, myMember_MedicineList_0, myMember_PatientDocuments_0, myMember_PatientReports_0, myMember_PopUpPage_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "PatientList":
        return myMember_PatientList_0;
      case "PatientDetails":
        return myMember_PatientDetails_0;
      case "ProfilePage":
        return myMember_ProfilePage_0;
      case "PatientInteraction":
        return myMember_PatientInteraction_0;
      case "Notification":
        return myMember_Notification_0;
      case "MedicineList":
        return myMember_MedicineList_0;
      case "PatientDocuments":
        return myMember_PatientDocuments_0;
      case "PatientReports":
        return myMember_PatientReports_0;
      case "PopUpPage":
        return myMember_PopUpPage_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
