/**
 * generated by Xtext 2.21.0
 */
package org.example.ehealthmanagement.xtext.formatting2;

import org.eclipse.xtext.formatting2.AbstractFormatter2;

@SuppressWarnings("all")
public abstract class EHealthManagementFormatter extends AbstractFormatter2 {
}
