package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_AllowedDatatypes extends EnumerationDescriptorBase {

  public EnumerationDescriptor_AllowedDatatypes() {
    super(0x59f9da20e62a4a82L, 0x8c2d8a77f06056f1L, 0x68bcf0507dc96087L, "AllowedDatatypes", "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304064508039");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_INTEGER_0 = new EnumerationDescriptor.MemberDescriptor("INTEGER", "INTEGER", 0x68bcf0507dc96088L, "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304064508040");
  private final EnumerationDescriptor.MemberDescriptor myMember_STRING_0 = new EnumerationDescriptor.MemberDescriptor("STRING", "STRING", 0x68bcf0507dc96089L, "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304064508041");
  private final EnumerationDescriptor.MemberDescriptor myMember_BOOLEAN_0 = new EnumerationDescriptor.MemberDescriptor("BOOLEAN", "BOOLEAN", 0x68bcf0507dc9608cL, "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304064508044");
  private final EnumerationDescriptor.MemberDescriptor myMember_VARCHAR_0 = new EnumerationDescriptor.MemberDescriptor("VARCHAR", "VARCHAR", 0x68bcf0507dc96090L, "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304064508048");
  private final EnumerationDescriptor.MemberDescriptor myMember_DATE_0 = new EnumerationDescriptor.MemberDescriptor("DATE", "DATE", 0x68bcf0507dc9e0bfL, "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304064540863");
  private final EnumerationDescriptor.MemberDescriptor myMember_IMAGE_0 = new EnumerationDescriptor.MemberDescriptor("IMAGE", "IMAGE", 0x68bcf0507dd3472eL, "r:68443fa0-31ea-4acf-a487-c0193440bf2c(NewLanguage.structure)/7547171304065156910");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x59f9da20e62a4a82L, 0x8c2d8a77f06056f1L, 0x68bcf0507dc96087L, 0x68bcf0507dc96088L, 0x68bcf0507dc96089L, 0x68bcf0507dc9608cL, 0x68bcf0507dc96090L, 0x68bcf0507dc9e0bfL, 0x68bcf0507dd3472eL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_INTEGER_0, myMember_STRING_0, myMember_BOOLEAN_0, myMember_VARCHAR_0, myMember_DATE_0, myMember_IMAGE_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "INTEGER":
        return myMember_INTEGER_0;
      case "STRING":
        return myMember_STRING_0;
      case "BOOLEAN":
        return myMember_BOOLEAN_0;
      case "VARCHAR":
        return myMember_VARCHAR_0;
      case "DATE":
        return myMember_DATE_0;
      case "IMAGE":
        return myMember_IMAGE_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
