/*
 * generated by Xtext 2.21.0
 */
package org.example.ehealthmanagement.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.example.ehealthmanagement.xtext.EHealthManagementRuntimeModule;
import org.example.ehealthmanagement.xtext.EHealthManagementStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EHealthManagementIdeSetup extends EHealthManagementStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EHealthManagementRuntimeModule(), new EHealthManagementIdeModule()));
	}
	
}
